apiVersion: v1
kind: Service
metadata:
  name: ideko-uc
spec:
  type: NodePort
  selector:
    component: ideko-uc
  ports:
  - name: node-red
    port: 8080 
    targetPort: 50017
  - name: monitoring
    port: 8484 
    targetPort: 50018

---
apiVersion: v1
kind: Pod
metadata:
  name: ideko-uc
  labels:
    component: ideko-uc
spec:
  containers:
  - name: ideko-uc
    image: ditas/ideko-use-case:001
    ports:
    - containerPort: 8080
    - containerPort: 8484
    volumeMounts:
    - name: blueprint
      mountPath: /opt/blueprint
  volumes:
  - name: blueprint
    hostPath:
      path: /home/cloudsigma/blueprint
      type: Directory
